name: Gradle Release

on:
  push:
    branches: [ "main" ]

jobs:
  create_git_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v3

      - name: GitHub Actor
        env: 
          GITHUB_ACTOR: ${{ github.actor }}   
        run: echo "$GITHUB_ACTOR"

      - name: GitHub Triggering Actor
        env: 
          GITHUB_TRIGGERING_ACTOR: ${{ github.triggering_actor }}   
        run: echo "$GITHUB_TRIGGERING_ACTOR"

      - name: Git Config
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Remove -SNAPSHOT from versionName
        run: ./gradlew removeSnapshot

      - name: Set the new versionName as an environment variable
        id: get_version_name
        run: |
          ./gradlew getVersionName --quiet --console=plain
          VERSION_NAME="$(./gradlew getVersionName --quiet --console=plain)"
          echo "::set-output name=version_name::$VERSION_NAME"

      - name: Git Commit
        run: |
          git add app/build.gradle
          echo "version_name: ${{ steps.get_version_name.outputs.version_name }}"
          git commit -m "chore: prepare release ${{ steps.get_version_name.outputs.version_name }}"

      - name: Git Tag
        run: |
          echo "version_name: ${{ steps.get_version_name.outputs.version_name }}"
          git tag ${{ steps.get_version_name.outputs.version_name }}

      - name: Git Push Tag
        run: |
          echo "version_name: ${{ steps.get_version_name.outputs.version_name }}"
          git push origin ${{ steps.get_version_name.outputs.version_name }}

      - name: Bump version
        run: ./gradlew bumpVersion

      - name: Add -SNAPSHOT to versionName
        run: ./gradlew addSnapshot

      - name: Git Commit
        run: |
          git add app/build.gradle
          git commit -m "chore: prepare for next development iteration"

      - name: Git Pull
        run: |
          git fetch
          git pull
      
      - name: Git Push
        run: |
          git push

  build_apk_artifact:
    needs: create_git_tag
    runs-on: ubuntu-latest
    steps:
      - name: Get the Git Tag name from the previous job
        run: echo "$TAG_NAME"
        # TODO

      - uses: actions/checkout@v4
        # Clone the Git repo with the Tag name from the previous job
        # TODO
      
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v3
      - run: ./gradlew assembleRelease

  sign_apk_artifact:
    needs: build_apk_artifact
    runs-on: ubuntu-latest
    steps:
      - name: Get APK file from previous job
        run: echo "$APK_FILE"
        # TODO

  upload_signed_apk:
    needs: sign_apk_artifact
    runs-on: ubuntu-latest
    steps:
      - name: Get signed APK file from previous job
        run: echo "$SIGNED_APK_FILE"
        # TODO

  publish_to_appstore:
    needs: upload_signed_apk
    runs-on: ubuntu-latest
    steps:
      - name: Get APK file URL from previous job
        run: echo "$APK_FILE_URL"
        # TODO
